// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "../components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //   className={`
// //     ${geistSans.variable} ${geistMono.variable}
// //     antialiased
// //     bg-gradient-to-br from-slate-50 via-white to-slate-100
// //     text-slate-800
// //     min-h-screen
// //   `}
// // >
// //   <Navbar />
// //   <div className="max-w-7xl mx-auto px-6 pb-10">
// //     {children}
// //   </div>
// // </body>

// //     </html>
// //   );
// // }
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "../components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Job Queue Dashboard",
//   description: "Queue Monitoring UI",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`
//           ${geistSans.variable} ${geistMono.variable}
//           antialiased
//           bg-gradient-to-br from-slate-100 via-slate-200 to-slate-300
//           text-slate-800
//           min-h-screen
//         `}
//       >
//         <Navbar />
//         <div className="max-w-7xl mx-auto px-6 pb-12">
//           {children}
//         </div>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Job Queue Dashboard",
  description: "Queue Monitoring UI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable}
          antialiased
          bg-slate-950
          text-slate-200
          min-h-screen
          overflow-x-hidden
          selection:bg-indigo-600 selection:text-white
        `}
      >
        {/* Softer radial glow (less foggy) */}
        <div className="fixed inset-0 -z-10 bg-[radial-gradient(circle_at_top,rgba(99,102,241,0.08),transparent_50%)]" />

        {/* Slight bottom fade for depth */}
        <div className="fixed inset-0 -z-10 bg-[linear-gradient(to_bottom,transparent,rgba(2,6,23,0.6))]" />

        <Navbar />

        {/* Main Container */}
        <main className="max-w-7xl mx-auto px-6 pt-8 pb-20">
          {children}
        </main>
      </body>
    </html>
  );
}
